services:
  # Minio
  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9090:9090"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    command: server /data --console-address ":9090"
    volumes:
      - ./data:/data
    networks:
      - minio-network

  # API C#
  api-csharp:
    container_name: api-csharp
    build:
      context: ./api-csharp
      dockerfile: Dockerfile
    ports:
      - "6000:6000" 
    depends_on:
      - db
      - minio
    networks:
      - back-network
      - db-network
      - minio-network
  
  # API Python (Flask)
  api-python:
    container_name: api-python
    build:
      context: ./api-python
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - back-network
      - front-network

  # Serveur Frontend (Nginx)
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    networks:
      - front-network

  # Base de données MySQL
  db:
    container_name: db
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: "1234"  
      MYSQL_DATABASE: "calculs"
      MYSQL_USER: "calcul_user"
      MYSQL_PASSWORD: "1234"
    ports:
      - "3306:3306" 
    volumes:
      - ./dbdata:/var/lib/mysql
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - db-network
      - pma-network

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - pma-network

volumes:
  dbdata:
  data:

networks:
  front-network:
    driver: bridge
  back-network:
    driver: bridge
  pma-network:
    driver: bridge
  db-network:
    driver: bridge
  minio-network:
    driver: bridge